### ISSUE TITLE
Periodically check battery while running

### ISSUE THREAD

**Issue by bigjosh** [bigjosh/Firmware#2]
Use WDT to wake so we can sleep the rest of the time.

Show blink pattern when voltage gets to too low, then deep sleep.

**Comment by ZachDunham** [comment]
Would love to get this working!

**Comment by bigjosh** [comment]
Hmmm... appears there is a twist. The battery voltage drops significantly when the amp starts pulling juice. The ideal solution would be to mute the amp every few seconds and take a clean voltage measurement - but users would not like this.  Maybe we need a lower "warm" voltage cut-off?

**Comment by bigjosh** [comment]
This is now implemented, but is it right? Needs testing.

**Comment by bigjosh** [comment]
Works, but needs refinement. Rolled into #15
