### ISSUE TITLE
Sleep between diagnostic blinks?

### ISSUE THREAD

**Issue by bigjosh** [bigjosh/Firmware#3]
We currently pull about 0.5mA while blinking a diagnostic code (currently only bad EEPROM CRC).

This currently happens for 120 secs before we go to sleep.

We could drop this to a few uA by sleeping between blinks.

Worth the extra code and complexity?

**Comment by ZachDunham** [comment]
@bigjosh IMO this seems like a small thing to prioritize and probably not worth the extra code and complexity.

**Comment by bigjosh** [comment]
This ended up being easy once the `sleepFor()` function was done. Besides the small power savings, this ended up saving code size since the `sleepFor()` function is reused and replaces several calls to ~delay_ms()`, which expand to relatively large loops.
