### ISSUE TITLE
Rewire AMP shutdown pin to RESET line to MCU can power it down.

### ISSUE THREAD

**Issue by bigjosh** [bigjosh/Firmware#4]
Deep sleep currently pulls 86uA, with the FMIC spec'ed at ~15uA in shutdown, the rest is likely coming from the amp (the ATTINY should be <5uA).   

Test to see if pulling SHUTDOWN cuts that. It is spec'ed to use only ~1uA.

**Comment by ZachDunham** [comment]
@bigjosh this would be great to test. The amp shutdown pin is wired to the MCU on the last rev.

**Comment by bigjosh** [comment]
This is implemented on PCB version PR9025 and higher, but need to test to make sure it works as expected.

**Comment by bigjosh** [comment]
Confirmed pre-productions boards pull 40uA in sleep.  Right order of magnitude (amp chip draws many mA if not shutdown), so closing #4.
